name: acarsng
homepage: https://github.com/airframesio/acarsng
description: Next-generation ACARS/VDL/HFDL/AERO decoder for RTL-SDRs
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  ffi: ^0.1.0
  meta: ^1.2.0
  more: ^2.7.0
dev_dependencies:
  test: ^1.15.0
